/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Dino(props) {
  const { nodes, materials } = useGLTF('/react-threejs/dino.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.03}>
        <mesh geometry={nodes.tyrannosaurus_rex1.geometry} material={nodes.tyrannosaurus_rex1.material} position={[0, 0, -500]}/>
      </group>
    </group>
  )
}

useGLTF.preload('/react-threejs/dino.glb')
